<?php

    $quotes = array(
        "Everyone is the other and no one is himself.",
        "Why are there beings at all instead of nothing? That is the question. Presumably it is not arbitrary question, \"Why are there beings at all instead of nothing\"- this is obviously the first of all questions. Of course it is not the first question in the chronological sense [...] And yet, we are each touched once, maybe even every now and then, by the concealed power of this question, without properly grasping what is happening to us. In great despair, for example, when all weight tends to dwindle away from things and the sense of things grows dark, the question looms.",
        "When tradition thus becomes master, it does so in such a way that what it transmits is made so inaccessible, proximally and for the most part, that it rather becomes concealed. Tradition takes what has come down to us and delivers it over to self-evidence; it blocks our access to those primordial \"sources\" from which the categories and concepts handed down to us have been in part quite genuinely drawn. Indeed it makes us forget that they have had such an origin, and makes us suppose that the necessity of going back to these sources is something which we need not even understand.",
        "But “nowhere” does not mean nothing; rather, region in general lies therein, and disclosedness of the world in general for essentially spatial being-in. Therefore, what is threatening cannot come closer from a definite direction within nearness, it is already “there” - and yet nowhere. It is so near that it is oppressive and takes one’s breath - and yet it is nowhere.",
        "...\"Nature\" is not to be understood as that which is just present-at-hand, nor as the power of Nature. The wood is a forest of timber, the mountain a quarry of rock; the river is water-power, the wind is wind \"in the sails\". As the \"environment\" is discovered, the \"Nature\" thus discovered is encountered too. If its kind of Being as ready-to-hand is disregarded, this \"Nature\" itself can be discovered and defined simply in its pure presence-at-hand. But when this happens, the Nature which \"stirs and strives\", which assails us and enthralls us as landscape, remains hidden. The botanist\"s plants are not the flowers of the hedgerow; the \"source\" which the geographer establishes for a river is not the \"springhead in the dale\".",
        "Even in expecting, one leaps away from the possible and gets a footing in the real. It is for its reality that what is expected is expected. By the very nature of expecting, the possible is drawn into the real, arising from it and returning to it.",
        "Body\", \"soul\", and \"spirit\" may designate phenomenal domains which can be detached as themes for definite investigations; within certain limits their ontological indefiniteness may not be important. When, however, we come to the question of man\"s Being, this is not something we can simply compute by adding together those kinds of Being which body, soul, and spirit respectively possess--kinds of being whose nature has not as yet been determined. And even if we should attempt such an ontological procedure, some idea of the Being of the whole must be presupposed.",
        "...Dasein itself--and this means also its Being-in-the-world--gets its ontological understanding of itself in the first instance from those entities which it itself is not but which it encounters \"within\" its world, and from the Being which they possess.",
        "The senses do not enable us to cognize any entity in its Being; they merely serve to announce the ways in which \"external\" Things within-the-world are useful or harmful for human creatures encumbered with bodies....they tell us nothing about entities in their Being.",
        "Dasein does not fill up a track or stretch ‘of life’ — one which is somehow present-at-hand — with the phases of its momentary actualities. It stretches itself along in such a way that its own being is constituted in advance as a stretching-along. The ‘between’ which relates to birth and death already lies in the being of Dasein … It is by no means the case that Dasein ‘is’ actual in a point of time, and that, apart from this, it is ‘surrounded’ by the non-actuality of its birth and death. Understood existentially, birth is not … something past in the sense of something no longer present-at-hand; and death is just as far from having the kind of being of something … not yet present-at-hand but coming along … Factical Dasein exists as born; and, as born, it is already dying, in the sense of being-towards-death. As long as Dasein factically exists, both the ‘ends’ and their ‘between’ *are*, and they are in the only way possible on the basis of Dasein’s being as *care* … As care, Dasein is the ‘between’.",
        "Being\" cannot be derived from higher concepts by definition, nor can it be presented through lower ones. But does this imply being no longer offers a problem? Not at all. We can infer only that \"Being\" cannot have the character of an entity. Thus we cannot apply to Being the concept of \"definition\" as presented in traditional logic, [...] which, within certain limits, provides a justifiable way of characterizing \"entities\".",
        "Dasein exists as an entity for which, in its Being, that Being is itself an issue. Essentially ahead of itself, it has projected itself upon its potentiality-for-Being before going on to any mere consideration of itself. In its projection it reveals itself as something which has been thrown. It has been thrownly abandoned to the ‘world’, and falls into it concernfully.(1) As care—that is, as existing in the unity of the projection which has been fallingly thrown—this entity has been disclosed as a “there”. As being with Others, it maintains itself in an average way of interpreting—a way which has been Articulated in discourse and expressed in language. Being-in-the-world has always expressed itself, and as Being alongside entities encountered within-the-world, it constantly expresses itself in addressing itself to the very object of its concern and discussing it. The concern of circumspective common sense is grounded in temporality—indeed in the mode of a making-present which retains and awaits. Such concern, as concernfully reckoning up, planning, preventing, or taking precautions, always says (whether audibly or not) that something is to happen ‘then’, that something else is to be attended to ‘beforehand’, that what has failed or eluded us ‘on that former occasion’ is something that we must ‘now’ make up for.(2)",
        "Being\" cannot be derived from higher concepts by definition, nor can it be presented through lower ones. But does this imply being no longer offers a problem? Not at all. We can infer only that \"Being\" cannot have the character of an entity. Thus we cannot apply to Being the concept of \"definition\" as presented in traditional logic, [...] which, within certain limits, provides a justifiable way of characterizing \"entities\".",
        "The term \"Being\" does not define that realm of entities which is uppermost when these are articulated conceptually according to genus and species: the \"universality\" of Being \"transcends\" any universality of genus.",
        "What could be more alien to the \"they\", lost in the manifold \"world\" of its concern, than the Self which has been individualized down to itself in uncanniness and been thrown in the \"nothing\"?",
        "In its factical existence, any particular Dasein either ‘has the time’ or ‘does not have it’. It either ‘takes time’ for something or ‘cannot allow any time for it’. Why does Dasein ‘take time’, and why can it ‘lose’ it? Where does it take time from? How is this time related to Dasein’s temporality?`,`Iedereen is de ander, en niemand is zichzelf.",
        "Die Wiederholung des Möglichen ist weder ein Wiederbringen des \"Vergangenen\" noch ein Zurückbinden der \"Gegenwart\" an das \"Überholte\". Die Wiederholung lässt sich, einem entschlossenen Sichentwerfen entspringend, nicht vom \"Vergangenen\" überreden, um es als das vormals Wirkliche nur wiederkehren zu lassen. Die Wiederholung erwidert viel mehr die Möglichkeit der dagewesenen Existenz.",
        "Has Dasein as itself ever freely decided, and will it ever be able to decide, whether it wants to come into \"Dasein\" or not?",
        "The lyricism of marginality may find inspiration in the image of the \“outlaw,\” the great social nomad, who prowls on the confines of a docile, frightened order.",
        "Justice must always question itself, just as society can exist only by means of the work it does on itself and on its institutions.",
        "As the archaeology of our thought easily shows, man is an invention of recent date. And one perhaps nearing its end.",
        "What strikes me is the fact that in our society, art has become something which is related only to objects and not to individuals, or to life. That art is something which is specialized or which is done by experts who are artists. But couldn\"t everyone\"s life become a work of art? Why should the lamp or the house be an art object, but not our life?",
        "...if you are not like everybody else, then you are abnormal, if you are abnormal , then you are sick. These three categories, not being like everybody else, not being normal and being sick are in fact very different but have been reduced to the same thing",
        "I don’t feel that it is necessary to know exactly what I am. The main interest in life and work is to become someone else that you were not in the beginning. If you knew when you began a book what you would say at the end, do you think that you would have the courage to write it\? What is true for writing and for ,love relationships is true also for life. The game is worthwhile insofar as we don’t know where it will end.",
        "The work of an intellectual is not to mould the political will of others; it is, through the analyses that he does in his own field, to re-examine evidence and assumptions, to shake up habitual ways of working and thinking, to dissipate conventional familiarities, to re-evaluate rules and institutions and to participate in the formation of a political will (where he has his role as citizen to play).",
        "Are you going to change yet again, shift your position according to the questions that are put to you, and say that the objections are not really directed at the place from which you are speaking? Are you going to declare yet again that you have never been what you have been reproached with being? Are you already preparing the way out that will enable you in your next book to spring up somewhere else and declare as you\"re now doing: no, no, I\"m not where you are lying in wait for me, but over here, laughing at you?\". \"What, do you imagine that I would take so much trouble and so much pleasure in writing, do you think that I would keep so persistently to my task, if I were not preparing – with a rather shaky hand – a labyrinth into which I can venture, into which I can move my discourse... in which I can lose myself and appear at last to eyes that I will never have to meet again. I am no doubt not the only one who writes in order to have no face. Do not ask who I am and do not ask me to remain the same: leave it to our bureaucrats and our police to see that our papers are in order. At least spare us their morality when we write.",
        "...it\"s my hypothesis that the individual is not a pre-given entity which is seized on by the exercise of power. The individual, with his identity and characteristics, is the product of a relation of power exercised over bodies, multiplicities, movements, desires, forces.",
        "From the idea that the self is not given to us, I think there is only one practical consequence: we have to create ourselves as a work of art.",
        "There is no power relation without the correlative constitution of a field of knowledge, nor any knowledge that does not presuppose and constitute at the same time power relations",
        "How much truth is contained in something can be best determined by making it thoroughly laughable and then watching to see how much joking around it can take. For truth is a matter that can withstand mockery, that is freshened by any ironic gesture directed at it. Whatever cannot withstand satire is false.",
        "We can trace the communitarian fantasy that lies at the root of all humanism back to the model of a literary society, in which participation through reading the canon reveals a common love of inspiring messages. At the heart of humanism so understood we discover a cult or club fantasy: the dream of the portentous solidarity of those who have been chosen to be allowed to read. In the ancient world—indeed, until the dawn of the modern nation-states—the power of reading actually did mean something like membership of a secret elite; linguistic knowledge once counted in many places as the provenance of sorcery. In Middle English the word \"glamour\" developed out of the word \"grammar\". The person who could read would be thought easily capable of other impossibilities.",
        "Wherever one encounters members of the human race, they always show the traits of a being that is condemned to surrealistic effort. Whoever goes in search of humans will find acrobats."
    );

?>
  