<?php
    $titles = array(
        "How I stopped worrying and learned to love the bomb",
        "10 things I hate about you...",
        "The life and times of Kevin McCloud",
        "The life and times of Connor McLeod",
        "Alex Mathie: Super-sub",
        "Being and Time",
        "Sein und Zeit",
        "Bubbles, Spheres and Foams - the work of Peter Sloterijk",
        "Archaeology of Knowledge",
        "New Model Island",
        "Universal Principles of Design",
        "Principea Mathematica",
        "The History of Western Philosophy",
        "How to do a cartwheel in 6 easy steps",
        "Does anyone remember Kid'n'Play?",
        "Sharky and George and other amazing morning cartoons...",
        "The life and times of Juninho",
        "Neil Hunt's nonsense pottery",
        "Polanyi's Tacit and Explicit knowledge explained",
        "The rise and fall of Ivan Drago",
        "How I fell in love with a Broccoli woman",
        "Hit Les - over the top!",
        "Looking for the heart of Saturday night...",
        "Manifesto del Futurismo",
        "The History of Derry, Maine",
        "Larry Renwick went axe-happy on a trout farm: He killed 60 fish",
        "Writers who use subtext are all cowards",
        "The Entertainers"
    );

    $headers = array(
        "Less is more",
        "Clearing",
        "Readiness-to-hand as a mode of Being",
        "Dasein",
        "Existenz",
        "Have you met the temp?",
        "Pouvoir/Savoir",
        "The Panoptican",
        "Real velourrrrrrr...",
        "The Gosling vs. Reynolds debate",
        "Fire, walk with me",
        "Imagined Communities",
        "Hello, hello there, is this Martha?",
        "Cover your shame Liz",
        "Author, Dreamweaver, Visionary. Plus Actor.",
        "The most significant televisual event since Quantum Leap",
        "I'm not Jesus Christ. I've come to accept that now.",
        "Cool it, Sanchez, or you'll get a knuckle supper!",
        "Maggots!? Maggots. Maggots. Maggots. Maggots.",
        "You'll be lucky if you get any of my lovely chicken if you keep up this kind of behaviour",
        "I've got two words for you: telly kinesis",
        "You win again Gravity!"
    );
?>